
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.1.02 EDK_J_SP2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_LEDS_8BIT_DEVICE_ID,
		XPAR_LEDS_8BIT_BASEADDR,
		XPAR_LEDS_8BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_8BIT_IS_DUAL
	},
	{
		XPAR_PUSH_BUTTONS_3BIT_DEVICE_ID,
		XPAR_PUSH_BUTTONS_3BIT_BASEADDR,
		XPAR_PUSH_BUTTONS_3BIT_INTERRUPT_PRESENT,
		XPAR_PUSH_BUTTONS_3BIT_IS_DUAL
	},
	{
		XPAR_SWITCHES_8BIT_DEVICE_ID,
		XPAR_SWITCHES_8BIT_BASEADDR,
		XPAR_SWITCHES_8BIT_INTERRUPT_PRESENT,
		XPAR_SWITCHES_8BIT_IS_DUAL
	},
	{
		XPAR_SSEG_DEVICE_ID,
		XPAR_SSEG_BASEADDR,
		XPAR_SSEG_INTERRUPT_PRESENT,
		XPAR_SSEG_IS_DUAL
	},
	{
		XPAR_SPI2_DATA_DEVICE_ID,
		XPAR_SPI2_DATA_BASEADDR,
		XPAR_SPI2_DATA_INTERRUPT_PRESENT,
		XPAR_SPI2_DATA_IS_DUAL
	},
	{
		XPAR_GPIO_DEVICE_ID,
		XPAR_GPIO_BASEADDR,
		XPAR_GPIO_INTERRUPT_PRESENT,
		XPAR_GPIO_IS_DUAL
	}
};


