#include "xparameters.h"

#define MEM ((volatile unsigned int *)XPAR_MICRON_RAM_MEM0_BASEADDR)

#define MAP(id) (*((volatile unsigned int*)(id)))
#define BTN  MAP(XPAR_PUSH_BUTTONS_3BIT_BASEADDR)
#define LED  MAP(XPAR_LEDS_8BIT_BASEADDR)
#define SW   MAP(XPAR_SWITCHES_8BIT_BASEADDR)
#define SSEG MAP(XPAR_SSEG_BASEADDR)

#define TIMER_0 ((unsigned int*)XPAR_TIMER_0_BASEADDR)
#define TIMER_1 ((unsigned int*)XPAR_TIMER_1_BASEADDR)
#define TIMER_2 ((unsigned int*)XPAR_TIMER_2_BASEADDR)
#define TIMER_3 ((unsigned int*)XPAR_TIMER_3_BASEADDR)

#define T0_TCSR0 MAP(XPAR_TIMER_0_BASEADDR)
#define T0_TLR0  MAP(XPAR_TIMER_0_BASEADDR + 0x4)
#define T0_TCR0  MAP(XPAR_TIMER_0_BASEADDR + 0x8)
#define T0_TCSR1 MAP(XPAR_TIMER_0_BASEADDR + 0x10)
#define T0_TLR1  MAP(XPAR_TIMER_0_BASEADDR + 0x14)
#define T0_TCR1  MAP(XPAR_TIMER_0_BASEADDR + 0x18)

#define T1_TCSR0 MAP(XPAR_TIMER_1_BASEADDR)
#define T1_TLR0  MAP(XPAR_TIMER_1_BASEADDR + 0x4)
#define T1_TCR0  MAP(XPAR_TIMER_1_BASEADDR + 0x8)
#define T1_TCSR1 MAP(XPAR_TIMER_1_BASEADDR + 0x10)
#define T1_TLR1  MAP(XPAR_TIMER_1_BASEADDR + 0x14)
#define T1_TCR1  MAP(XPAR_TIMER_1_BASEADDR + 0x18)

#define T2_TCSR0 MAP(XPAR_TIMER_2_BASEADDR)
#define T2_TLR0  MAP(XPAR_TIMER_2_BASEADDR + 0x4)
#define T2_TCR0  MAP(XPAR_TIMER_2_BASEADDR + 0x8)
#define T2_TCSR1 MAP(XPAR_TIMER_2_BASEADDR + 0x10)
#define T2_TLR1  MAP(XPAR_TIMER_2_BASEADDR + 0x14)
#define T2_TCR1  MAP(XPAR_TIMER_2_BASEADDR + 0x18)

#define T3_TCSR0 MAP(XPAR_TIMER_3_BASEADDR)
#define T3_TLR0  MAP(XPAR_TIMER_3_BASEADDR + 4)
#define T3_TCR0  MAP(XPAR_TIMER_3_BASEADDR + 8)
#define T3_TCSR1 MAP(XPAR_TIMER_3_BASEADDR + 12)
#define T3_TLR1  MAP(XPAR_TIMER_3_BASEADDR + 16)
#define T3_TCR1  MAP(XPAR_TIMER_3_BASEADDR + 20)

#define ISR MAP(XPAR_OPB_INTC_0_BASEADDR)
#define IPR MAP(XPAR_OPB_INTC_0_BASEADDR + 4)
#define IER MAP(XPAR_OPB_INTC_0_BASEADDR + 8)
#define IAR MAP(XPAR_OPB_INTC_0_BASEADDR + 12)
#define SIE MAP(XPAR_OPB_INTC_0_BASEADDR + 16)
#define CIE MAP(XPAR_OPB_INTC_0_BASEADDR + 20)
#define IVR MAP(XPAR_OPB_INTC_0_BASEADDR + 24)
#define MER MAP(XPAR_OPB_INTC_0_BASEADDR + 28)

#define LCD_RX MAP(XPAR_LCD_UART_BASEADDR)
#define LCD_TX MAP(XPAR_LCD_UART_BASEADDR + 4)
#define LCD_SR MAP(XPAR_LCD_UART_BASEADDR + 8)
#define LCD_CR MAP(XPAR_LCD_UART_BASEADDR + 12)

#define INT_SPI XPAR_SPI_IP2INTC_IRPT_MASK
#define INT_T3  XPAR_TIMER_3_INTERRUPT_MASK 
#define INT_T2  XPAR_TIMER_2_INTERRUPT_MASK 
#define INT_T1  XPAR_TIMER_1_INTERRUPT_MASK 
#define INT_T0  XPAR_TIMER_0_INTERRUPT_MASK 

#define SPI(n) (*((volatile unsigned int*)(XPAR_SPI_BASEADDR+n)))
#define SPICR SPI(0x60)
#define SPISR SPI(0x64)
#define SPIDTR SPI(0x68)
#define SPIDRR SPI(0x6C)
#define SPISSR SPI(0x70)
#define SPITX_STATE SPI(0x74)
#define SPIRX_STATE SPI(0x78)
#define SPI_DGIE SPI(0x1C)
#define SPI_IPISR SPI(0x20)
#define SPI_IPIER SPI(0x28)
#define SPI_IPIF SPI(0x40)

#define SPI2 MAP(XPAR_SPI2_DATA_BASEADDR)

#define GPIO MAP(XPAR_GPIO_BASEADDR)
