#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:C:\CPE329\final\system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = C:/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = spartan3e

DEVICE = xc3s500efg320-4

LANGUAGE = vhdl

SEARCHPATHOPT =  -lp C:/edk_user_repository/lib

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) \
                   $(MICROBLAZE_0_LIBG_OPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

FINAL_OUTPUT_DIR = Final
FINAL_OUTPUT = $(FINAL_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf
MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

BRAMINIT_ELF_FILES =  $(FINAL_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe microblaze_0 $(FINAL_OUTPUT) 

ALL_USER_ELF_FILES = $(FINAL_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM).do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM).do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM).do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti -X C:/CPE329/final/ -E C:/CPE329/final/


LIBRARIES =  \
       microblaze_0/lib/libxil.a 
VPEXEC = virtualplatform/vpexec.exe

LIBSCLEAN_TARGETS = microblaze_0_libsclean 

PROGRAMCLEAN_TARGETS = Final_programclean 

CORE_STATE_DEVELOPMENT_FILES = C:\edk_user_repository\MyProcessorIPLib\pcores\lcd_fsl_v1_00_a\hdl\vhdl\lcd_fsl.vhd

WRAPPER_NGC_FILES = implementation/microblaze_0_wrapper.ngc \
implementation/ilmb_wrapper.ngc \
implementation/dlmb_wrapper.ngc \
implementation/dlmb_cntlr_wrapper.ngc \
implementation/ilmb_cntlr_wrapper.ngc \
implementation/lmb_bram_wrapper.ngc \
implementation/mb_opb_wrapper.ngc \
implementation/leds_8bit_wrapper.ngc \
implementation/push_buttons_3bit_wrapper.ngc \
implementation/switches_8bit_wrapper.ngc \
implementation/rs232_port_wrapper.ngc \
implementation/micron_ram_wrapper.ngc \
implementation/micron_ram_util_bus_split_0_wrapper.ngc \
implementation/dcm_0_wrapper.ngc \
implementation/sseg_wrapper.ngc \
implementation/timer_0_wrapper.ngc \
implementation/timer_1_wrapper.ngc \
implementation/sseg_d_wrapper.ngc \
implementation/opb_intc_0_wrapper.ngc \
implementation/timer_2_wrapper.ngc \
implementation/timer_3_wrapper.ngc \
implementation/spi_wrapper.ngc \
implementation/lcd_fsl_0_wrapper.ngc \
implementation/fsl_v20_0_wrapper.ngc \
implementation/spi2_wrapper.ngc \
implementation/spi2_data_wrapper.ngc \
implementation/gpio_wrapper.ngc \
implementation/lcd_uart_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(BITGEN_UT_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION FINAL
#################################################################

FINAL_SOURCES = final.c lcd.c 

FINAL_HEADERS = lcd.h 

FINAL_CC = mb-gcc
FINAL_CC_SIZE = mb-size
FINAL_CC_OPT = -O2
FINAL_CFLAGS = -save-temps
FINAL_CC_SEARCH = # -B
FINAL_LIBPATH = -L./microblaze_0/lib/ # -L
FINAL_INCLUDES = -I./microblaze_0/include/  -IC:/CPE329/final/ # -I
FINAL_LFLAGS = # -l
FINAL_LINKER_SCRIPT = 
FINAL_LINKER_SCRIPT_FLAG = #-Wl,-T -Wl,$(FINAL_LINKER_SCRIPT) 
FINAL_CC_DEBUG_FLAG = # -[g|gstabs]
FINAL_CC_PROFILE_FLAG = # -pg
FINAL_CC_GLOBPTR_FLAG= # -mxl-gp-opt
FINAL_MODE = executable
FINAL_LIBG_OPT = -$(FINAL_MODE) microblaze_0
FINAL_CC_INFERRED_FLAGS= -mno-xl-soft-mul -mxl-pattern-compare -mhard-float -mno-xl-soft-div -mcpu=v6.00.b 
FINAL_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
FINAL_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
FINAL_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
FINAL_OTHER_CC_FLAGS= $(FINAL_CC_GLOBPTR_FLAG)  \
                  $(FINAL_CC_START_ADDR_FLAG) $(FINAL_CC_STACK_SIZE_FLAG) $(FINAL_CC_HEAP_SIZE_FLAG)  \
                  $(FINAL_CC_INFERRED_FLAGS)  \
                  $(FINAL_LINKER_SCRIPT_FLAG) $(FINAL_CC_DEBUG_FLAG) $(FINAL_CC_PROFILE_FLAG) 
