
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.1.02 EDK_J_SP2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Exception Handler Table for MicroBlaze Processor
*
*******************************************************************/

#include "microblaze_exceptions_i.h"
#include "xparameters.h"


