
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.1.02 EDK_J_SP2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtmrctr.h"

/*
* The configuration table for devices
*/

XTmrCtr_Config XTmrCtr_ConfigTable[] =
{
	{
		XPAR_TIMER_0_DEVICE_ID,
		XPAR_TIMER_0_BASEADDR
	},
	{
		XPAR_TIMER_1_DEVICE_ID,
		XPAR_TIMER_1_BASEADDR
	},
	{
		XPAR_TIMER_2_DEVICE_ID,
		XPAR_TIMER_2_BASEADDR
	},
	{
		XPAR_TIMER_3_DEVICE_ID,
		XPAR_TIMER_3_BASEADDR
	}
};


