
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.1.02 EDK_J_SP2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xspi.h"

/*
* The configuration table for devices
*/

XSpi_Config XSpi_ConfigTable[] =
{
	{
		XPAR_SPI_DEVICE_ID,
		XPAR_SPI_BASEADDR,
		XPAR_SPI_FIFO_EXIST,
		XPAR_SPI_SPI_SLAVE_ONLY,
		XPAR_SPI_NUM_SS_BITS
	}
};


